---
title: ES6笔记 - Promise对象
date: 2016-05-30  21:30:32
tags:
    - ES6
    - JavaScript
---



Promise是ES6新增的用来解决JavaScript异步编程（asynchronous programming）问题的对象，JavaScript的日常编码中需要处理大量的基于事件-回调方式的异步代码，例如用户点击一个button触发一个回调函数的执行。Node的出现以及其以callback代替events的编程方式，进一步的加强了JavaScript的异步编程模式的概念。

### 异步编程形式

JavaScript引擎是基于单线程的Event loop模式，单线程意味着同一时间上只能有一段代码执行，所以引擎本身需要记录所有需要处理的任务。这些任务被保存在一个事件队列Event queue中，JavaScript引擎结束当前任务后会检测事件队列继续执行下个任务，Event loop在引擎内部用来检测代码执行和调度事件队列。

在浏览器端异步模式是基于事件模型，如

```js
button.addEventListener('click' , function(event){
  console.log('按钮的click事件处理')
});
console.log('立即执行的代码');
```

服务器端Node的callback异步模式

fs.readFile('file.txt' , function(err , data){
  if(err){
    throw err ;
  }
  console.log(data);
});

### 异步的多层嵌套

通常我们要编写某个代码模块，某块或功能本身可能递归嵌套了一系列异步子模块，这是通常代码会长成这个样子：

```js
function task(){
  methodA(function(){
    methodB(function(){
      methodC(function(){
        //...
      });

    });
  });
}
```
所以最终代码会层层嵌套，这里`})`通常被[callback hell][1]，随着处理问题的复杂度的提升，[callback hell][1]的问题会越来越严重，代码的可读性卓然下降。Promise对象的引入的目的之一就是解决这个问题。

### Promise简介

Promise对象是一个用来处理延迟或异步任务的对象，它是一个代理，代表了一个尚未结束但会在未来某个时间点发生的操作。例如以下是在node中读取文件的一个操作

```js
let promise = readFile('file.txt');
```
`readFile()`不会立即发生，而是返回一个promise对象，代表一个异步的读取文件的操作。Promise对象拥有生命周期的概念：

+ pending state，启示待定状态，操作未完成或失败。
+ fulfilled state，操作成功完成。
+ rejected state，操作失败。

以上`readFile`返回的promise对象处于pending状态，处于pending状态的promise对象在操作成功完成后会转换到fulfilled状态，如果操作失败则转换为rejected状态。Promise对象的`[[PromiseState]] `属性用来记录对象所处的状态。

### Promise的基本使用

Promise构造器接收一个executor函数类型的参数，形式如下：

```js
function executor(resolve , reject){

}
```
executor函数封装的通常是一个异步操作，它的两个参数`resolve`和`reject`是函数类型，executor函数在传入Promise后会立即执行，一旦异步操作完成后，成功则调用resolve函数返回结果只并设置promise对象为fulfilled状态，当发生错误或异常时则调用reject函数并设置promise对象为rejected状态。在调用resolve函数和reject函数时，都可以传入任何必须的参数。

所以可以创建Promise对象，

```js
let promise = new Promise(function(resolve , reject){
    // 通常是async 操作
    //
    if(success){
      resolve(result);
    }else{
      reject();
    }
});
```
在创建完成后，可以使用Promise的`then()`方法来监听promise对象状态的变换，`then()`接受两个函数类型的参数——`onFulfilled`，`onRejected`，如

```js
promise.then(function onFulfilled(){
  // 操作成功完成
},function onRejected(){
  // 操作失败
})
```
在promise对象变为fulfilled状态后，`onFulfilled`函数会被调用，相反，promise对象变为rejected状态后，`onRejected`函数会被调用。两个参数是可选的，所以还有以下两种调用形式

```js
// 1. 只监听fulfilled状态
promise.then(function onFulfilled(){
  // to do
});

// 2. 只监听rejected状态

promise.then(undefined , function onRejected(){
  // to do
});
```
以下是一个完整的使用Node读取文件的例子

```js
let fs = require('fs');

function readFile(filePath){

  let promise = new Promise(function(resolve , reject){

    // node下异步读取文件操作
    fs.readFile(filePath , {encoding:'utf-8'} , function(err , data){
      if(err){
        reject(err)
      }
      resolve(data);
    });
  });
  return promise;
}

let filePath = __dirname + '/file.txt';


let promise = readFile(filePath);

promise.then(function(fileContent){
  console.log('read file succeed');
  console.log(fileContent);
} , function(err){
  console.log('read file failed');
  console.log(err);
});
```

以上例子中`readFile()`函数接收文件路径，定义异步读取文件的executor函数，并返回promise对象，外部调用`readFile()`函数后会马上获得返回的promise对象，使用`then()`方法分别添加promise对象状态的监听函数，executor函数会马上执行，读取文件成功后会调用resolve函数并传入文件内容，失败调用resolve函数传入err对象。

需要注意的是在新建Promise对象后executor函数会马上执行，但在调用resolve或reject函数时会把它们当做任务添加到事件队列，之后再执行，正如setTimeout用来延迟执行任务一样，如

```js
setTimeout(function(){
  console.log(1);
},1);
console.log(2);
```
会输出
```
2
1
```
对比来说Promise的实现，比如

```js
let promise = new Promise(function(resovle){
  console.log(1);
  resovle()
});
promise.then(function(){
  console.log(2);
});
console.log(3);
```
会输出
```
1
3
2
```

### catch()方法

Promise的`catch()`方法用来处理当promise对象转变为rejected状态后的回调，类似于promise.then(undefined , onRejected)，当executor执行抛出错误时也会调用该方法，所以在进行错误处理时该方法会比较有用，如

```js
let promise = new Promise(function(resovle , reject){
  reject();
});
promise.catch(function(){
  console.log('promise reject');
})
```
会输出

```
promise reject
```

抛出错误后，会调用`catch()`方法，如

```js
let promise = new Promise(function(resolve , reject){
  throw new Error('executor error');
});
promise.catch(function(error){
  console.log(error.message)
});
```
会输出

```
executor error
```
以上例子等价于
```js
let promise = new Promise(function(resolve , reject){
  try{
    throw new Error('executor error');
  }catch(error){
    reject(error)
  }
});

promise.catch(function(error){
  console.log(error.message)
});

```

### Promise链式结构

Promise的`then()`方法和`catch()`方法其实都会返回一个新的Promise对象，因此利用这个特点可以实现Promise的链式调用结构。

```js
let p1 = new Promise(function(resolve, reject) {
    resolve(100);
});

p1.then(function(value) {
    console.log(value);
}).then(function() {
    console.log("done");
});
```
会输出
```
100
done
```

以上例子等价于

```js
let p1 = new Promise(function(resolve, reject) {
    resolve(100);
});

let p2 =p1.then(function(value) {
    console.log(value);
});

p2.then(function() {
    console.log("done");
});
```

p2只有在p1 resovle之后才执行。此外在链式调用中，可以从一个Promise传值给下一个，

```js
let p1 = new Promise(function(resolve, reject) {
    resolve(100);
});

p1.then(function(value) {
    console.log(value);         // 100
    return value * 2;
}).then(function(value) {
    console.log(value);         // 200
});

```
错误的处理同样也可以使用链式结构，这需要使用`catch()`方法。

```js
let p1 = new Promise(function(resovle , reject){
  resovle(100);
});
p1.then(function(value){
  console.log(value);
  throw new Error('failed');
}).catch(function(error){
  console.log(error.message); // failed
});
```

如果返回的值是一个Promise对象，则么下个chain方法的调用状态取决于这个返回的Promise对象的状态，如

```js
let p1 = new Promise(function(resolve, reject) {
    resolve(100);
});

let p2 = new Promise(function(resolve, reject) {
    resolve(101);
});

p1.then(function(value) {
    console.log(value);     // 100
    return p2;
}).then(function(value) {
    console.log(value);     // 101
});
```
以上例子等价于

```js
let p1 = new Promise(function(resolve, reject) {
    resolve(100);
});

let p2 = new Promise(function(resolve, reject) {
    resolve(101);
});

let p3 = p1.then(function(value) {
    console.log(value);     // 100
    return p2;
});
p3.then(function(value) {
    console.log(value);     // 101
});
```

可以看出使用链式调用结构，可以避免callback hell问题，只要将所有异步操作封装进Promise然后按照顺序一级级返回即可，

```js
let promise = new Promise(function methodA(resolve , reject){
  asyncMethodA(){
    if(success){
      resovle(result);
    }
    reject(new Error());
  }
  asyncMethodA();
}).then(function(value){
  asyncMethodB(){
     if(success){
      resovle(result);
    }
      reject(new Error());
    }
  asyncMethodB();
},function(error){
  // 错误处理
}).then(function(value){
  asyncMethodC(){
   if(success){
    resovle(result);
  }
    reject(new Error());
  }
  asyncMethodC();
},function(error){
  // 错误处理
});
```
### Promise.resolve()方法

Promise的静态方法`Promise.resolve()`接收单一参数，并返回一个状态为fulfilled的Promise对象，该方法可接收的参数类型包括

1.参数可以是基本数据类型

```js
// 参数为基本数据类型
let promise = Promise.resovle(100);
promise.then(function(value){
  console.log(value); // 100
});
```
2.可以是对象类型
```js
// 参数为数组类型
let promise = Promise.resovle([100,200,300]);
promise.then(function(value){
  console.log(value); // [100, 200, 300]
});
```
3.可以是另一个Promise对象，那么该方法会将该对象返回，

```js
let promiseA = new Promise(function(resolve){
  resolve(100);
});

let promiseB = Promise.resolve(promiseA);
promiseB.then(function(value){
  console.log(value); // 100
})
```
4.一个thenable对象。所谓thenable对象是指的一个有`then()`方法的对象，如
```js
let thenable = {
  then: function(resolve , reject){
    resolve(100);
  }
};

let promise = Promise.resolve(thenable);
promise.then(function(value){
  console.log(value);
});
```

### Promise.reject()方法

同`Promise.resolve()`一样，Promise.reject()也是一个静态方法，但它返回的是一个状态为rejected的Promise对象，它的参数类型与`Promise.resolve()`完全一样。

```js
let promise = Promise.reject('fail reason');
promise.then(function(reason){
  console.log(reason); // fail reason
});
```

### Promise.all()

`Promise.all()`接受一个包含多个Promise对象的iterable类型的参数，并返回一个Promise对象，可以监听它们的状态，当所有Promise对象都转换为fulfilled后才会将自己的状态设置为fulfilled，如果有其中一个Promise对象状态转换为了rejected，那么它就会转换为rejected状态。此方法可以用来监听多个异步任务的状态来执行下一步操作的行为。

```js
let p1 = new Promise(function(resolve, reject) {
    resolve(1);
});

let p2 = new Promise(function(resolve, reject) {
    resolve(2);
});

let p3 = new Promise(function(resolve, reject) {
    resolve(3);
});

let p4 = Promise.all([p1, p2, p3]);

p4.then(function(value) {
    console.log(Array.isArray(value));  // true
    console.log(value[0]);              // 1
    console.log(value[1]);              // 2
    console.log(value[2]);              // 3
});
```

如果有一个Promise最终转换为rejected状态，那么`Promise.all()`返回的对象就转换为rejected状态

```js
let p1 = new Promise(function(resolve, reject) {
    resolve(1);
});

let p2 = new Promise(function(resolve, reject) {
    resolve(2);
});

let p3 = new Promise(function(resolve, reject) {
    reject('failed');
});

let p4 = Promise.all([p1, p2, p3]);

p4.then(function(value) {

},function(message){
  console.log(message); // failed
});
```
### Promise.race()方法

`Promise.race()`方法同样接受一个包含多个Promise对象的iterable类型的参数，并返回一个Promise对象，只要其中任何Promise对象的状态改变了，那么返回的Promise对象的状态也会相应改变。


```js
let p1 = new Promise(function(resolve, reject) {
  setTimeout(function(){
    resolve(1); // 最先执行
  },100);

});

let p2 = new Promise(function(resolve, reject) {
    setTimeout(function(){
      reject('failed');
    },200);
});

let p3 = new Promise(function(resolve, reject) {
    setTimeout(function(){
      resolve(3);
    },300);
});

let p4 = Promise.race([p1, p2, p3]);

p4.then(function(value) {
  // p1优先执行了
  console.log(value); // 1
},function(message){
  console.log(message); // 不会被调用了
});
```

### 参考

+ [Promise][3]
+ [Concurrency model and Event Loop][1]
+ [callback hell][2]
+ [Managing Node.js Callback Hell with Promises, Generators and Other Approaches][4]
+ [The JavaScript Event Loop: Explained][5]
+ [Understanding the Node.js Event Loop][6]
+ [Promises/A+][7]

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop
[2]: http://callbackhell.com/
[3]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
[4]: https://strongloop.com/strongblog/node-js-callback-hell-promises-generators/
[5]: http://blog.carbonfive.com/2013/10/27/the-javascript-event-loop-explained/
[6]: https://nodesource.com/blog/understanding-the-nodejs-event-loop/
[7]: https://promisesaplus.com/